version: "3.8"
services:
  frontend:
  {%- if values.docker_window == 'custom' %}
    image: ${{ values.docker_generic }}/${{ values.docker_organization }}/${{ values.componentId }}:latest
  {%- else %}
    image: ${{ values.docker_organization }}/${{ values.componentId }}:latest
  {%- endif %}
    ports:
      - protocol: tcp
        target: 80
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256MB
        reservations:
          cpus: "0.1"
          memory: 128MB
