apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: spec_project
  title: Spec Project
  description: Kong/Kubernetes Artifacts generator via Spec
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform-templates
    - kong
    - kubernetes

spec:
  owner: veecode/platform
  type: devops
  parameters:  
    ### Project Configuration
    - title: Catalog Details
      required:
        - componentId
        - owner
      properties:
        componentId:
          title: Project name
          type: string
          description: Name of the project. ex Viacep_app.
          pattern: '^([a-z0-9]|[.]|[_]|[-])*$'
          ui:autofocus: true
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          ui:widget: textarea
          ui:options:
            rows: 1
          description: Tell us more about your project
          default: "Artifacts generator via Spec."
        domain:
          title: Project Host
          type: string
          description: Name of host project. ex rest.apr.vee.codes.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              
    ### Spec Configuration
    - title: Spec Configuration
      required:
        - inputspec
      properties:
        inputspec:
          title: Input Spec
          description: Insert Spec
          type: string
          ui:widget: textarea
          ui:autofocus: true
          ui:placeholder: |
          
            apiVersion: backstage.io/v1alpha1
              kind: Component
              metadata:
                name: backstage
              spec:
                type: library
                owner: CNCF
                lifecycle: experimental
          ui:options:
            rows: 20
            
    ### Cluster Configuration
    - title: Cluster Settings
      properties:
        clusterResource:
          title: Select a Cluster from our catalog
          type: object
          ui:field: ResourcePicker
          ui:options:
            catalogFilter:
              kind: [Cluster]

   ### Spec Configuration
    - title: Spec Configuration
      required:
        - specPublish
        - specPublishBranch
      description: Define which repository your spec will be published in
      properties:
        specPublishBranch:
                  title: Branch name
                  type: string
                  description: the spec will be added to this branch
        specTags:
          title: Tags
          type: string
          description: Inputs tags separated by comma(,)
        specPublish:
          type: string
          ui:field: RepoUrlSelector
          ui:options:
            allowedHosts:
              - github.com

    ### Location Configuration
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          description: Choose a location to create the SpecProject Pipeline
          ui:field: RepoUrlSelector
          ui:options:
            allowedHosts:
              - github.com
        visibility:
          title: Repository visibility
          type: string
          enum:
            - public
            - private
          enumNames:
            - 'Public'
            - 'Private'
          default: private
          
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton      
        values:
          componentId: ${{ parameters.componentId }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          domain: ${{ parameters.domain }}
          #Spec input
          inputspec: ${{ parameters.inputspec}}
          #Cluster configuration 
          cluster_name: ${{ parameters.clusterResource.name }}
          cluster_type: ${{ parameters.clusterResource.cluster_type }}
          cluster_public_ip: ${{ parameters.clusterResource.public_ip }}
          #Spec configuration
          specPublish: ${{ (parameters.specPublish | parseRepoUrl).owner }}/${{ (parameters.specPublish | parseRepoUrl).repo }}
          specPublishRepo: ${{ (parameters.specPublish | parseRepoUrl).repo }}
          specPublishBranch: ${{ parameters.specPublishBranch }}
          specTags: ${{ parameters.specTags }}
          #location configuration      
          repoUrl: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}/${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
          host: ${{ parameters.repoUrl | parseRepoUrl | pick('host') }}
          
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: Spec Name ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: ${{ parameters.visibility }}
    
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}